### ISSUE TITLE
Screenshots and status

### ISSUE THREAD

**Issue by Ygarr** [APercy/some_more_trains#1]
Please add screenshots to projects and status info about completion status for probably one of the most useful mods.
![205015310_10224677287177940_2104334592669984895_n](https://user-images.githubusercontent.com/14309871/144725696-0de73e5e-f79c-496c-a2bf-82f15363616e.jpg)
![206245692_10224670818776234_3080736416495318799_n](https://user-images.githubusercontent.com/14309871/144725698-41170503-bf22-4542-8f27-a395132ab98d.jpg)

**Comment by APercy** [comment]
I'm a chaotic person, I'll try...
